<template>
  <v-col cols="12" md="6">
    <v-sheet class="d-flex bg-gray">
      <div class="pa-2 rounded-ts rounded-bs bg-v-dark-green">
        <v-icon class="text-white icon-calendar">mdi-calendar</v-icon>
      </div>
      <div class="d-flex align-center ga-2 py-2 px-8 text-white rounded-te rounded-be bg-v-green">
        <p>{{ date }}</p>
        <p>-</p>
        <p>{{ time }}</p>
      </div>
    </v-sheet>
  </v-col>
</template>

<script setup lang="ts">
  // Code generated by ChatGPT XD
  import { getDate } from '@/utils/date';
  import { getHour } from '@/utils/hour';

  const date = getDate();
  const time = ref('');
  let intervalId: number | undefined;

  const updateTime = () => {
    time.value = getHour();
  }
  const setupClock = () => {
    updateTime();
    const now = new Date();
    const secondsUntilNextMinute = 60 - now.getSeconds();

    setTimeout(() => {
      updateTime();
      intervalId = setInterval(updateTime, 60000);
    }, secondsUntilNextMinute * 1000);
  };

  onMounted(() => {
    setupClock();
  });
  onUnmounted(() => {
    if (intervalId) {
      clearInterval(intervalId);
    }
  });
</script>

<style scoped lang="scss">
  .icon-calendar {
    font-size: 35px;
  }
</style>
