/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/app': RouteRecordInfo<'/app', '/app', Record<never, never>, Record<never, never>>,
    '/herramientas': RouteRecordInfo<'/herramientas', '/herramientas', Record<never, never>, Record<never, never>>,
    '/iniciar-reporte-pilotos': RouteRecordInfo<'/iniciar-reporte-pilotos', '/iniciar-reporte-pilotos', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/personal': RouteRecordInfo<'/personal', '/personal', Record<never, never>, Record<never, never>>,
    '/pilotos': RouteRecordInfo<'/pilotos', '/pilotos', Record<never, never>, Record<never, never>>,
    '/reporte-pilotos': RouteRecordInfo<'/reporte-pilotos', '/reporte-pilotos', Record<never, never>, Record<never, never>>,
  }
}
